app = "medibot-dark-surf-5830"
primary_region = "ams"

[build]
  build-target = "telegram-bot"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[deploy]
  strategy = "rolling"

[mounts]
  source = "medibot_data"
  destination = "/data"

