version: 1
disable_existing_loggers: false

formatters:
  json:
    format: '{"timestamp": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "stack_trace": "%(exc_text)s"}'


loggers:
  root:
    level: INFO
    handlers:
    - stdout

  third_party:
    level: WARNING
    handlers:
      - stdout
    propagate: true

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout
